import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import Link from 'next/link'
import { useEffect, useState } from 'react'

export default function Home() {
  const [data, setData] = useState();

 
  const apiKey = process.env.NEXT_PUBLIC_NAME;
  const url = `https://api.nasa.gov/techtransfer/patent/?q=10&engine&api_key=${apiKey}`
  const getTechTransferData = async () => {
    const res = await axios.get(url)
    const info = await res.data;
    console.log(info);
    setData(info);
  }
    useEffect(() => {
      getTechTransferData();
    }, [])
  
  return (
    <>
      <Head>
        <title>Nasa API</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main className="main">
        <div className='polyDiv' >
        <button className='polyButton'>
          <Link href="/polychromatic">Polychromatic</Link>
        </button>


        </div>
           <div className='mainCont'>
              {
                  data && data.results.map((tech, index) => {
                  return (
              
                       <div className='homeImages' key={index}>
                           {
                                tech && tech.map((t, ind) => {
                                 if(ind ===10){
                                 return (
                                 <Image className='images' src={t}
                                   alt={t}
                                   key={ind}
                                   width={200}
                                   height={200}
                                 />
                                 )
                               }
                             })
                           }
                      </div>
                        )
                 })
             }
      </div>
      </main>
    </>
  )
}
